### ISSUE TITLE
Irregular errors when copying and pasting entries from other calendars

### ISSUE THREAD

**Issue by tomasz1986** [39aldo39/Radicale-DecSync#2] opened 2020-02-20 22:18 UTC
The errors happen when copying entries from a different calendar (which is just a static ICS file), and then pasting them into a calendar, which uses Radicale with the DecSync plugin. They are irregular, i.e. usually everything works smoothly, but from time to time, something suddenly goes wrong. After that, Radicale keeps spamming the log file with errors. Only restarting Radicale makes everything work again.

I am attaching a relevant part of the log file below. The repeated errors are basically this:

```
ERROR: An exception occurred during PUT request on '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/62c790d9-7a19-445a-8f4a-4afcb2d16482.ics': DecSync: Invalid .decsync-info
```

I am not sure what the problem is about, as the `.decsync-info` file itself does exist and its content always seems to be `{"version":1}`.

One possibly important detail may be that I usually copy and paste multiple entries at once.

[radicale.log](https://github.com/39aldo39/Radicale-DecSync/files/4233261/radicale.log)

**Comment by 39aldo39** [comment] 2020-02-22 22:04
Thanks for the report! Unfortunately, I don't really know what goes wrong. I suspect it isn't the `.decsync-info`, but something else. The error code for this error is 1, which might also be sent for a crash or something like that.

**Comment by tomasz1986** [comment] 2020-03-02 04:45
The problem has occurred again today. I have enabled DEBUG log beforehand, although I am not sure whether there is any useful information there.

This is what happened when trying to copy and paste several events from an ICS file calendar to a Radicale-DecSync calendar.

```
2020-03-02 13:33:39,111 - [256c] DEBUG: Sanitized script name: ''
2020-03-02 13:33:39,111 - [256c] DEBUG: Sanitized path: '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/'
2020-03-02 13:33:39,112 - [256c] INFO: Successful login: 'tomasz86'
2020-03-02 13:33:39,119 - [958] ERROR: An exception occurred during REPORT request on '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/': DecSync: Invalid .decsync-info
2020-03-02 13:33:39,119 - [38ac] ERROR: An exception occurred during REPORT request on '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/': DecSync: Invalid .decsync-info
2020-03-02 13:33:39,119 - [2bec] ERROR: An exception occurred during REPORT request on '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/': DecSync: Invalid .decsync-info
2020-03-02 13:33:39,119 - [21d0] ERROR: An exception occurred during REPORT request on '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/': DecSync: Invalid .decsync-info
2020-03-02 13:33:39,120 - [38f8] ERROR: An exception occurred during REPORT request on '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/': DecSync: Invalid .decsync-info
2020-03-02 13:33:39,120 - [256c] ERROR: An exception occurred during REPORT request on '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/': DecSync: Invalid .decsync-info
2020-03-02 13:33:39,125 - [321c] INFO: REPORT request for '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/' with depth '1' received from 127.0.0.1 using 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Thunderbird/60.9.1 Lightning/6.2.9.1'
2020-03-02 13:33:39,126 - [321c] DEBUG: Request headers:
{'CONTENT_LENGTH': '298',
 'CONTENT_TYPE': 'text/xml; charset=utf-8',
 'GATEWAY_INTERFACE': 'CGI/1.1',
 'HTTP_ACCEPT': 'text/xml',
 'HTTP_ACCEPT_CHARSET': 'utf-8,*;q=0.1',
 'HTTP_ACCEPT_ENCODING': 'gzip, deflate',
 'HTTP_ACCEPT_LANGUAGE': 'en-US,en;q=0.5',
 'HTTP_AUTHORIZATION': 'Basic **masked**',
 'HTTP_CACHE_CONTROL': 'no-cache',
 'HTTP_CONNECTION': 'keep-alive',
 'HTTP_DEPTH': '1',
 'HTTP_DNT': '1',
 'HTTP_HOST': 'localhost:5232',
 'HTTP_PRAGMA': 'no-cache',
 'HTTP_USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) '
                    'Gecko/20100101 Thunderbird/60.9.1 Lightning/6.2.9.1',
 'PATH_INFO': '/tomasz86/calendars-90208231-950b-5a65-7a7f-5ff788ffda62/',
 'QUERY_STRING': '',
 'REMOTE_ADDR': '127.0.0.1',
 'REMOTE_HOST': '',
 'REQUEST_METHOD': 'REPORT',
 'SCRIPT_NAME': '',
 'SERVER_NAME': 'XXX',
 'SERVER_PORT': '5232',
 'SERVER_PROTOCOL': 'HTTP/1.1',
 'SERVER_SOFTWARE': 'WSGIServer/0.2',
 'wsgi.errors': <_io.StringIO object at 0x000002437103E0D0>,
 'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
 'wsgi.input': <_io.BufferedReader name=26452>,
 'wsgi.multiprocess': False,
 'wsgi.multithread': False,
 'wsgi.run_once': False,
 'wsgi.url_scheme': 'http',
 'wsgi.version': (1, 0)}
```
The main inconvenience is the fact that a manual intervention, i.e. stopping and restarting Radicale and the plugin is required to restart the synchronisation. Would it be possible to have some kind of an automatic recovery in such a case?

**Comment by 39aldo39** [comment] 2020-04-30 18:30
I probably found the cause while working on something else. When writing to a file, I forgot to close it. This means that the program will open more and more files until the maximum number allowed is reached (which I found was 1024). Then, when it reads a file, it interprets it as an empty file. As an empty `.decsync-info` is invalid, it shows these errors.

It will be fixed in the next version. In the meantime, the only workaround is to restart Radicale occasionally.

**Closed by 39aldo39** 2020-04-30 18:30 UTC

**Comment by tomasz1986** [comment] 2020-05-01 03:43
Thank you very much. I dealt with the problem by copying and pasting the events in smaller numbers, and restarting Radicale when needed. It was not pretty, but did the job.
